### ISSUE TITLE
Add option to disable cron hooks

### ISSUE THREAD

**Issue by markusdenhoff** [blankogmbh/kirby-git-commit-and-push-content#12]
Add an option to disable the cron hook routes.

eg. `c::set('gcapc-cron-hooks-enabled', false);`

See also: #11

**Comment by Pascalmh** [comment]
Closed by commit https://github.com/blankogmbh/kirby-git-commit-and-push-content/commit/2118b281fc4353888ea7f630c2876693c23bd073
