### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by tjeerdytsma** [blankogmbh/kirby-git-commit-and-push-content#2]
Cannot get it working yet.
My content folder was already a sub repository, so I skipped the step 'Create a new git repository for your content' in the installation instructions. I followed the instructions under 'Download and configure the Plugin'. 
When I change content in the panel I just see my changes as unstaged files (not as commits) in my local repository and nothing is pushed to the remote.

**Comment by Pascalmh** [comment]
Make sure the Git.php folder isn't empty - looks like github does not include the submodules in the .zip it provides.

**Comment by tjeerdytsma** [comment]
The Git.php folder is not empty.

**Comment by Pascalmh** [comment]
Are you on Windows? Try adding this to your config: `c::set('gcapc-windowsMode', true);` you can also try to set the path to your git manually using `c::set('gcapc-gitBin', true);`.

If that still doesn't do the trick for you can try debugging in the helpers.php using the [Git.php](http://kbjr.github.io/Git.php/) options `GitRepo->test_git`, `Git::is_repo`.

**Comment by fivenp** [comment]
One of the main problems is having the webserver running under a different account then the file owner...

While the Plugin is trying to modify your content/.git/index.lock file (obviously being called from Git.php via the webserver-user) Git.php is throwing an error similar to "fatal: Unable to create '<pathto>/content/.git/index.lock': Permission denied" 

Solution -> Check the file rights and don't forget to add the according ssh keys of the webserver user to your github/bitbucket account... :)

**Comment by Pascalmh** [comment]
There is a link that gives a solution to this problem - you can find it in the [options section](https://github.com/Pascalmh/kirby-git-commit-and-push-content#options) - https://gist.github.com/jexchan/2351996

**Comment by Pascalmh** [comment]
ref #3
