### ISSUE TITLE
Update git dependency

### ISSUE THREAD

**Issue by tobiastom** [blankogmbh/kirby-git-commit-and-push-content#25]
It seems that this project requires the 0.1 version of `pascalmh/git.php`. Unfortunately this does not exist. For now there is only a `v0.1.1-rc`.

This happens when I try to install this plugin:

	$ composer require blankogmbh/kirby-git-commit-and-push-content
	Using version ^1.4 for blankogmbh/kirby-git-commit-and-push-content
	./composer.json has been updated
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Your requirements could not be resolved to an installable set of packages.
	
	  Problem 1
	    - Installation request for blankogmbh/kirby-git-commit-and-push-content ^1.4 -> satisfiable by blankogmbh/kirby-git-commit-and-push-content[1.4.0].
	    - blankogmbh/kirby-git-commit-and-push-content 1.4.0 requires pascalmh/git.php ^0.1 -> satisfiable by pascalmh/git.php[v0.1.1-rc] but these conflict with your requirements or minimum-stability.
	
	
	Installation failed, reverting ./composer.json to its original content.

**Comment by markusdenhoff** [comment]
@Pascalmh is this related to #21?

**Comment by tobiastom** [comment]
Works great now. Thank you.
