### ISSUE TITLE
Error with checking existence of Git.php submodule

### ISSUE THREAD

**Issue by jake** [blankogmbh/kirby-git-commit-and-push-content#26]
This [commit](https://github.com/blankogmbh/kirby-git-commit-and-push-content/commit/bd45077) introduced an error for me. I resolved it by changing the `initRepo` check it adds to use `__DIR__` and `DS` instead of hardcoded relative paths.

    if (file_exists(__DIR__ . DS . 'Git.php' . DS. 'Git.php')) {
        require __DIR__ . DS . 'Git.php' . DS. 'Git.php';
    } else {
        require kirby()->roots()->index() .
        DS . 'vendor' . DS . 'pascalmh' . DS . 'git.php' . DS . 'Git.php';
    }

**Comment by Pascalmh** [comment]
Looks good, would you like to create a Pull Request for it?

**Comment by jake** [comment]
sure thing, I also spotted another typo so I'll push two up 👍
