### ISSUE TITLE
git config of php/apache user not set

### ISSUE THREAD

**Issue by MrApe** [blankogmbh/kirby-git-commit-and-push-content#3]
To make a commit, git needs `user.name` and `user.email`. If not set, all commits will silently fail. Setting it as normal user (even as the one apache is running as) does not help. This may be an issue of git.php.

However, setting the respective config entries system wide, solves the problem:

    sudo git config --add --system user.name "example"
    sudo git config --add --system user.email "mail@example.com"

Unfortunately, this overwrites the defaults. Any better solution??

**Comment by markusdenhoff** [comment]
Have you tried to set name and email just for the specific repository?

```
cd /path/to/repo
git config user.name "example"
git config user.email "mail@example.com"
```

I think the reason why you can’t save the settings as the apache user is that this user probably has no home dir so git can’t save the settings there.

**Comment by MrApe** [comment]
This is a good idea. I didn't try this. In fact, Apache runs with my user, so the home config should be writable.

**Comment by markusdenhoff** [comment]
Interesting! Actually the setup works pretty well on all our servers (mainly Ubuntu) and development machines (OS X). 

But if it’s not an issue with your git config it’s a Git.php issue. So I’m closing this one here. Thanks for your feedback! :)
