### ISSUE TITLE
Add configuration value for the path to the repository

### ISSUE THREAD

**Issue by tobiastom** [blankogmbh/kirby-git-commit-and-push-content#31]
Currently the plugin assume that the content directory is a separate repository. I don't see a good reason for that, so I would like to use the complete site as a repository. 

I would create a pull request that implements a configuration option for the path to the repository, if you would accept it. :)

**Comment by Pascalmh** [comment]
We needed two different repositories for the content and the rest of the side so we could deploy to a dev/staging environment and a live environment.

However the Pull Request is much appreciated - thank you in advance! It would be great if the default settings and behaviour wouldn't be affected (so you probably need to add a new setting).
