### ISSUE TITLE
user changes not located in content folder

### ISSUE THREAD

**Issue by MrApe** [blankogmbh/kirby-git-commit-and-push-content#4]
The plugin connects to hooks triggered if a user is created or edited, but the changed account files are not in the content folder and therefor are not versioned.

**Comment by Pascalmh** [comment]
Good Point! Same goes for Avatars, I will kick those out as there is no chance to version it at the moment

**Comment by MrApe** [comment]
I have forked it and will send you a pull request. Best would be to make it optionally with seperate repos.
