### ISSUE TITLE
Not working when `site.txt` is changed

### ISSUE THREAD

**Issue by wottpal** [blankogmbh/kirby-git-commit-and-push-content#46]
Maybe Kirby doesn't fire any hooks for the site-settings or what else could be the problem? And when I save any other page after I've modified `site.txt` (via *Menu > Settings*) it commits & pushes all changes together.

<img width="160" alt="bildschirmfoto 2017-08-19 um 12 36 17" src="https://user-images.githubusercontent.com/3930150/29485910-0a074f6a-84db-11e7-985b-3ebe42caf81a.png">

Dennis

**Comment by Pascalmh** [comment]
The `panel.site.update` is not implemented. The hook needs to be added to the [git-commit-and-push-content.php](https://github.com/blankogmbh/kirby-git-commit-and-push-content/blob/master/git-commit-and-push-content.php).
