### ISSUE TITLE
Editing helpers.php

### ISSUE THREAD

**Issue by johnchourajr** [blankogmbh/kirby-git-commit-and-push-content#6]
Hey, Just had a quick question.

I just followed the install guide, and have a separate repo made for content. I'm pushing that repo, and the main repo to the same VPS, do you have any tips on how I can get this working on my VPS? Do I need to edit the helpers.php file to specify where my repos are?

My current repos are private and are located here: https://github.com/johnchourajr/grandfb-content

Here is my current helpers.php file content.

```
<?php

require_once('Git.php/Git.php');

/**
 * Compose Commit message, appends " by Username"
 *
 * @param string $commitMessage
 *
 * @return false
 */
function gitCommit($commitMessage)
{
    $debugMode = c::get('debug', false);
    $branch = c::get('gcapc-branch', 'dev');
    $pull = c::get('gcapc-pull', true);
    $push = c::get('gcapc-push', true);
    $commit = c::get('gcapc-commit', true);
    $gitBin = c::get('gcapc-gitBin', '/../grandfb-content/');
    $windowsMode = c::get('gcapc-windowsMode', false);
    /*
     * Setup git environment
     */
    if ($windowsMode) {
        Git::windows_mode();
    }
    if ($gitBin) {
        Git::set_bin($gitBin);
    }

    $repo = Git::open('../content');

    if ($debugMode) {
        if (!$repo->test_git()) {
            echo 'git could not be found or is not working properly. ' . Git::get_bin();
            exit;
        }

        if (!Git::is_repo($repo)) {
            echo '$repo is not an instance of GitRepo';
            exit;
        }
    }

    /*
     * Git Pull, Commit and Push
     */
    if ($pull) {
        $repo->checkout($branch);
        $repo->pull('origin', $branch);
    }
    if ($commit) {
        $repo->add('.');
        $repo->commit($commitMessage . ' by ' . site()->user());
    }
    if ($push) {
        $repo->push('origin', $branch);
    }

    return false;
}

```

**Comment by Pascalmh** [comment]
you shouldn't be editing the helpers.php or for that matter, any of the files of this plugin - with the next update they would be lost.

You can overwrite the [options](https://github.com/blankogmbh/kirby-git-commit-and-push-content#options) in your config.*.php using `c::set('gcapc-OPTIONNAME', 'yourValue');` 

That said, this is probably wrong - `$gitBin = c::get('gcapc-gitBin', '/../grandfb-content/');` this option should point the your git installation (on a Mac it's `/usr/bin/git` by default), not to your getkirby content folder. Make sure your VPS has git installed and then point this option to the git installation.

**Comment by johnchourajr** [comment]
So if my git installation is installed in ```/usr/local/bin/git``` I would put the following in my config/config.php file?

```c::set('gcapc-gitBin', '/usr/local/bin/git');```

**Comment by Pascalmh** [comment]
Yes, you might want to make use of the [Multi-environment setup](http://getkirby.com/blog/multi-environment-setup).
